services:
  main:
    image: shiftinv/github-webhook-filter
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: "8080"
    ports:
      - '127.0.0.1:18080:8080'
